CREATE DATABASE DATA;
USE DATA;
CREATE TABLE IRIS_DATA(
    SEPAL_LENGTH FLOAT,
    SEPAL_WIDTH FLOAT,
    PETAL_LENGTH FLOAT,
    PETAL_WIDTH FLOAT,
    SPECIES VARCHAR(50)
);
SHOW DATABASES;
SHOW TABLES;

## SELECT QUERY ##
SELECT * FROM IRIS_DATA;

## FILTERING ROWS THROUGH WHERE CLAUSE ##
SELECT * FROM IRIS_DATA WHERE SPECIES = 'SETOSA';

## AVERAGE ##
SELECT AVG(SEPAL_LENGTH) AS AVG_SEPAL FROM IRIS_DATA;

## MAXIMUM
SELECT MAX(PETAL_WIDTH) AS MAX_PETAL FROM IRIS_DATA;

## MINIMUM ##
SELECT MIN(SEPAL_WIDTH) AS MIN_SEPAL FROM IRIS_DATA;

## COUNT ##
SELECT COUNT(*) AS TOTAL_ROWS FROM IRIS_DATA;

## GROUPBY ##
SELECT SPECIES, AVG(SEPAL_LENGTH) AS AVG_SEPAL_LENGTH FROM IRIS_DATA GROUP BY SPECIES;
SELECT SPECIES, AVG(PETAL_LENGTH) AS AVG_PETAL_LENGTH FROM IRIS_DATA GROUP BY SPECIES;

## SUM ##
SELECT SUM(SEPAL_LENGTH) AS TOTAL_SEPAL_LENGTH FROM IRIS_DATA;
SELECT SUM(PETAL_WIDTH) AS SUM_PETAL_WIDTH FROM IRIS_DATA WHERE SEPAL_LENGTH > 6;

## JOIN TABLE ##
CREATE TABLE SPECIES_INFO(
SPECIES VARCHAR(50),
FLOWER_COLOR VARCHAR(20));

INSERT INTO SPECIES_INFO(SPECIES, FLOWER_COLOR) VALUES
('SETOSA','BLUE'),
('VERSICOLOR','PURPLE'),
('VIRGINICA','WHITE');

SELECT * FROM SPECIES_INFO;

SELECT I.SEPAL_LENGTH,I.PETAL_LENGTH,I.SPECIES,S.FLOWER_COLOR FROM IRIS_DATA I JOIN 
SPECIES_INFO S ON I.SPECIES= S.SPECIES;

## ORDERBY - SORTING ##
SELECT * FROM IRIS_DATA ORDER BY PETAL_LENGTH DESC LIMIT 10;

## SUBQUERY - FIND SPECIES WITH HIGHEST AVERAGE SEPAL LENGTH ##
SELECT SPECIES FROM IRIS_DATA GROUP BY SPECIES ORDER BY AVG(SEPAL_LENGTH) DESC LIMIT 1;

## CREATE INDEXES (IF FILTERING/SEARCHING A COLUMN OFTEN) ##
CREATE INDEX IDX_SPECIES ON IRIS_DATA(SPECIES);

## USE LIMIT TO REDUCE THE OUTPUT SIZE ##
SELECT * FROM IRIS_DATA LIMIT 10;

## USE WHERE CLAUSE TO FILTER BEFORE GROUP BY OR JOIN ##
SELECT SPECIES, AVG(SEPAL_LENGTH) FROM IRIS_DATA WHERE SEPAL_LENGTH > 5 GROUP BY SPECIES;

